# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\roptions.proto\"\x94\x01\n\x12Skeletons3dOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x11\n\tgroup_ids\x18\x03 \x03(\r\x12\x15\n\x06x_axis\x18\x04 \x01(\x0b\x32\x05.Axis\x12\x15\n\x06y_axis\x18\x05 \x01(\x0b\x32\x05.Axis\x12\x15\n\x06z_axis\x18\x06 \x01(\x0b\x32\x05.Axis\"\"\n\x04\x41xis\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x62\x06proto3')
)




_SKELETONS3DOPTIONS = _descriptor.Descriptor(
  name='Skeletons3dOptions',
  full_name='Skeletons3dOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='Skeletons3dOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='Skeletons3dOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_ids', full_name='Skeletons3dOptions.group_ids', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_axis', full_name='Skeletons3dOptions.x_axis', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_axis', full_name='Skeletons3dOptions.y_axis', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_axis', full_name='Skeletons3dOptions.z_axis', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=166,
)


_AXIS = _descriptor.Descriptor(
  name='Axis',
  full_name='Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Axis.start', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='Axis.end', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=202,
)

_SKELETONS3DOPTIONS.fields_by_name['x_axis'].message_type = _AXIS
_SKELETONS3DOPTIONS.fields_by_name['y_axis'].message_type = _AXIS
_SKELETONS3DOPTIONS.fields_by_name['z_axis'].message_type = _AXIS
DESCRIPTOR.message_types_by_name['Skeletons3dOptions'] = _SKELETONS3DOPTIONS
DESCRIPTOR.message_types_by_name['Axis'] = _AXIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Skeletons3dOptions = _reflection.GeneratedProtocolMessageType('Skeletons3dOptions', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONS3DOPTIONS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:Skeletons3dOptions)
  ))
_sym_db.RegisterMessage(Skeletons3dOptions)

Axis = _reflection.GeneratedProtocolMessageType('Axis', (_message.Message,), dict(
  DESCRIPTOR = _AXIS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:Axis)
  ))
_sym_db.RegisterMessage(Axis)


# @@protoc_insertion_point(module_scope)
